Workaround for godot empty array synced bug
TheDuckCow/godot-road-generator pull request #87
Opened 2023-03-31 11:20 UTC by TheDuckCow

Appears to be working when copied into the wheel steal project. The match lane issue was happening when they were properly de-synced but then zero array length, hence failing on reference [0].

Closes https://github.com/TheDuckCow/godot-road-generator/issues/86

2023-04-04 03:23 UTC, bdog2112 commented
What are the steps to re-create the problem that you're addressing? (It may be a different problem than the one I am thinking.)

Using the following testing steps, the arrays are still synced:

- Create a new Scene with RoadNetwork node as root
- Select root node and click "Create>2x2 road" in 3D view
- Save Scene and close it
- Re-open Scene
- Select first RoadPoint, go to Edit RoadPoint panel, and click "+" to add a lane
- Observe that adding a lane to the first RoadPoint also adds a lane to the second RoadPoint. **The arrays are synced**.

To implement a non-holistic fix simply change the number of lanes from the defaults, save, and re-open. Then, the individual RoadPoints will behave as expected (as long as they don't have the default values).

A holistic fix entails one of two possible solutions:

1. Fix Godot ;-)
2. Insure that RoadGen ALWAYS saves all the elements of RoadPoint arrays to Scene files. (This rule probably also applies to arrays in all other classes, as well.)

2023-04-04 03:24 UTC, bdog2112 requested changes
Lanes still synced under certain conditions. See notes in the "Conversation" thread.

2023-04-18 14:40 UTC, TheDuckCow commented
Note to self: move default export vars out of the export var def, and move into init, and verify that default values are saved to the scene files when used.

2023-04-23 02:27 UTC, bdog2112 commented
Just wanted to add that [this post](https://github.com/TheDuckCow/godot-road-generator/pull/88#issuecomment-1518918247) appears related to the synced array problem and further supports the potential effectiveness of the proposed fix.

2023-04-23 17:17 UTC, TheDuckCow commented
Great work investigating this - I've made the change, found I could not reproduce [following your instructions here](https://github.com/TheDuckCow/godot-road-generator/pull/88#issuecomment-1518918247) (a sign the fix worked), and then when reverting the change, I found it immediately occurred just as you described. So I'm pretty confident this is working with this update!

2023-04-27 18:55 UTC, bdog2112 approved these changes
Followed test steps and no longer encountered synced array bug. All GUT tests passed. Looks good!

2023-04-27 23:39 UTC, merged